server_address: 127.0.0.1
ports: 8080,8081
server_name: myserver
client_max_body_size: 1048576
error_pages:
  404: /errors/404.html
  500: /errors/500.html

route /upload:
  methods: POST
  redirection: /thank-you

route /thank-you:
  methods: GET
  root: www
  default_file: thank-you.html
  directory_listing: off

route /static:
  methods: GET
  root: ./public
  default_file: index.html
  directory_listing: off
  cgi:
    .py: /usr/bin/python3
